puts "The students of my cohort at Makers Academy"
puts "------------"
puts "Dr. Hannibal Lecter"
puts "darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "alex De large"
puts "The Alien"
puts "Terminator"
puts "Freddy Kruger"
puts "The Joker"
